# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: brad.price
  password:
  pool: 5

development:
  <<: *default
  database: produciton_development

test:
  <<: *default
  database: produciton_test

production:
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>
